version: '3.8'

services:
  app:
    build: .
    container_name: concordato_app
    ports:
      - "8501:8501"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=gK2VDL-2&2<I
      - DB_NAME=ilan_db
      - HEADLESS=true
      # API Key config.py'den okunacak, istenirse buraya eklenebilir:
      # - OPENAI_API_KEY=sk-...
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - app_network
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: concordato_db
    environment:
      - MYSQL_ROOT_PASSWORD=gK2VDL-2&2<I
      - MYSQL_DATABASE=ilan_db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network
    ports:
      - "3307:3306" # Yerel MySQL ile çakışmaması için dışarı 3307 olarak açtık
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

networks:
  app_network:
    driver: bridge

volumes:
  db_data:

